// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzyhebvxpdfototecdlg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6eWhlYnZ4cGRmb3RvdGVjZGxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMTM5NzksImV4cCI6MjA2Njc4OTk3OX0.3B355N_aDwCj6bgDXG4DtwDPG3Gsb1vlhWK105sUWoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);